# Generated by Django 4.2.17 on 2025-03-30 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0003_menuitem_cost_price_menuitem_current_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('KITCHEN', 'Kitchen Staff'), ('WAITER', 'Waiter/Waitress'), ('DELIVERY', 'Delivery Person')], default='CASHIER', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'permissions': [('manage_staff', 'Can manage staff members'), ('view_sales_reports', 'Can view sales reports'), ('manage_inventory', 'Can manage inventory'), ('process_orders', 'Can process orders'), ('manage_menu', 'Can manage menu items')],
            },
        ),
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_ORDER', 'Created Order'), ('UPDATE_ORDER', 'Updated Order'), ('CANCEL_ORDER', 'Cancelled Order'), ('ADD_ITEM', 'Added Menu Item'), ('UPDATE_ITEM', 'Updated Menu Item'), ('DELETE_ITEM', 'Deleted Menu Item'), ('ADD_INVENTORY', 'Added Inventory'), ('OTHER', 'Other Activity')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Activity',
                'verbose_name_plural': 'Staff Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
