# Generated by Django 5.1.1 on 2025-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('KITCHEN', 'Kitchen Staff'), ('WAITER', 'Waiter/Waitress'), ('DELIVERY', 'Delivery Person'), ('CUSTOMER', 'Customer')], default='CASHIER', max_length=20),
        ),
    ]
