# Generated by Django 5.1.1 on 2025-03-30 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_order_contact_number_order_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': [('manage_staff', 'Can manage staff members'), ('view_sales_reports', 'Can view sales reports'), ('manage_inventory', 'Can manage inventory'), ('process_orders', 'Can process orders'), ('manage_menu', 'Can manage menu items'), ('manage_customers', 'Can manage customers')], 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='blacklist_reason',
            field=models.TextField(blank=True, help_text='Reason for blacklisting this customer'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='blacklisted_at',
            field=models.DateTimeField(blank=True, help_text='When this customer was blacklisted', null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='blacklisted_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who blacklisted this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='Whether this customer is blacklisted'),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_ORDER', 'Created Order'), ('UPDATE_ORDER', 'Updated Order'), ('CANCEL_ORDER', 'Cancelled Order'), ('ADD_ITEM', 'Added Menu Item'), ('UPDATE_ITEM', 'Updated Menu Item'), ('DELETE_ITEM', 'Deleted Menu Item'), ('ADD_INVENTORY', 'Added Inventory'), ('BLACKLIST_CUSTOMER', 'Blacklisted Customer'), ('UNBLACKLIST_CUSTOMER', 'Removed Customer from Blacklist'), ('OTHER', 'Other Activity')], max_length=20),
        ),
    ]
