# Generated by Django 5.1.4 on 2025-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_order_split_bill_order_split_type_order_split_ways'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
