# Generated by Django 5.1.4 on 2025-04-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_preparation_time',
            field=models.PositiveIntegerField(default=30, help_text='Estimated preparation time in minutes'),
        ),
    ]
