# Generated by Django 4.2.17 on 2025-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_order_estimated_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table_number',
            field=models.CharField(blank=True, help_text='Table assignment', max_length=20, null=True),
        ),
    ]
