# Generated by Django 4.2.17 on 2025-04-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_remove_reservation_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
